FROM tensorflow/tensorflow:2.10.1-gpu

RUN rm /etc/apt/sources.list.d/cuda.list

RUN apt-get update
RUN apt-get install -y unzip graphviz curl musescore3

RUN pip install --upgrade pip

WORKDIR /app

COPY ./requirements.txt /app
RUN pip install -r /app/requirements.txt

ENV PYTHONPATH="${PYTHONPATH}:/app"
